ALTER TABLE users
ADD COLUMN first_name VARCHAR(255),
ADD COLUMN last_name VARCHAR(255),
ADD COLUMN phone VARCHAR(255),
ADD COLUMN bio VARCHAR(1000),
ADD COLUMN profile_picture VARCHAR(255),
ADD COLUMN facebook VARCHAR(255),
ADD COLUMN twitter VARCHAR(255),
ADD COLUMN linkedin VARCHAR(255),
ADD COLUMN instagram VARCHAR(255),
ADD COLUMN country VARCHAR(255),
ADD COLUMN city VARCHAR(255),
ADD COLUMN postal_code VARCHAR(255),
ADD COLUMN tax_id VARCHAR(255);