apiVersion: v1
kind: Secret
metadata:
  name: erp-secrets
  namespace: erp-namespace
type: Opaque
stringData:
  # MySQL Container & Spring Data
  MYSQL_ROOT_PASSWORD: "root_password_change_me"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "erp_password"
  
  # RabbitMQ
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
  # Keys specifically for RabbitMQ official image if needed
  RABBIT_USER: "guest"
  RABBIT_PASS: "guest"
  # PostgreSQL for Chat
  POSTGRES_PASSWORD: "chat_password_secret"
