server:
  port: 8082

spring:
  application:
    name: creditos-web
  datasource:
    url: jdbc:mysql://localhost:3306/db_creditos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  flyway:
    repair-on-migrate: true
    validate-on-migrate: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/auth/jwks

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
